export const FONTS = new Map<string, string>([
  [ 'babylonica', 'Babylonica' ],
  [ 'bilbo', 'Bilbo' ],
  [ 'bilbo-swash-caps', 'Bilbo Swash Caps' ],
  [ 'caveat', 'Caveat' ],
  [ 'crafty-girls', 'Crafty Girls' ],
  [ 'delius', 'Delius' ],
  [ 'edu-tas-beginner', 'Edu TAS Beginner' ],
  [ 'lavishly-yours', 'Lavishly Yours' ],
  [ 'nothing-you-could-do', 'Nothing You Could Do' ],
  [ 'playpen-sans', 'Playpen Sans' ],
  [ 'playwrite-nz', 'Playwrite NZ' ],
  [ 'schoolbell', 'Schoolbell' ],
  [ 'shadows-into-light', 'Shadows Into Light' ],
  [ 'shadows-into-light-two', 'Shadows Into Light Two' ],
  [ 'short-stack', 'Short Stack' ],
  [ 'story-script', 'Story Script' ],
  [ 'sue-ellen-francisco', 'Sue Ellen Francisco' ],
]);